--1 
SELECT TUTORS.TT_ID, TUTORS.TT_NAME, COUNT(DISTINCT ED_STUDENT) AS COUNT
FROM TUTORS 
LEFT JOIN EDUCATION 
ON (TUTORS.TT_ID = EDUCATION.ED_TUTOR)
GROUP BY TUTORS.TT_NAME, TUTORS.TT_ID
ORDER BY TUTORS.TT_ID;

--2 
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME, COUNT(DISTINCT EDUCATION.ED_TUTOR) AS COUNT
FROM STUDENTS 
JOIN EDUCATION 
ON (STUDENTS.ST_ID = EDUCATION.ED_STUDENT)
GROUP BY STUDENTS.ST_ID, STUDENTS.ST_NAME
ORDER BY STUDENTS.ST_ID;

--3
SELECT TUTORS.TT_ID, TUTORS.TT_NAME, COUNT(EDUCATION.ED_DATE) AS CLASSES_COUNT
FROM TUTORS
JOIN EDUCATION
ON (TUTORS.TT_ID = EDUCATION.ED_TUTOR)
WHERE EXTRACT (MONTH FROM EDUCATION.ED_DATE) = 9 AND EXTRACT(YEAR FROM EDUCATION.ED_DATE) = 2012
GROUP BY TUTORS.TT_ID, TUTORS.TT_NAME
HAVING COUNT(EDUCATION.ED_DATE) = 
	(SELECT MAX(COUNT(EDUCATION.ED_DATE))
		FROM EDUCATION 
		WHERE EXTRACT (MONTH FROM EDUCATION.ED_DATE) = 9 AND EXTRACT(YEAR FROM EDUCATION.ED_DATE) = 2012
		GROUP BY EDUCATION.ED_TUTOR
	);
	
--4
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME, AVG(EDUCATION.ED_MARK) AS AVG_MARK
FROM STUDENTS
LEFT JOIN EDUCATION ON (STUDENTS.ST_ID = EDUCATION.ED_STUDENT)
GROUP BY STUDENTS.ST_ID, STUDENTS.ST_NAME
ORDER BY ST_ID;

--5
SELECT ST_ID, ST_NAME,  LISTAGG(convert(sb_name, 'UTF8', 'AL16UTF16'), ',') WITHIN GROUP (ORDER BY SB_NAME) AS SB_NAMES, MAX_MARK
FROM EDUCATION 
LEFT JOIN SUBJECTS ON (EDUCATION.ED_SUBJECT = SUBJECTS.SB_ID)
RIGHT JOIN 
(SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME, MAX(EDUCATION.ED_MARK) AS MAX_MARK 
FROM EDUCATION 
RIGHT JOIN STUDENTS ON (STUDENTS.ST_ID = ED_STUDENT)
GROUP BY STUDENTS.ST_ID, STUDENTS.ST_NAME)
ON (ST_ID = ED_STUDENT AND ED_MARK = MAX_MARK)
GROUP BY ST_ID, ST_NAME,MAX_MARK
ORDER BY ST_ID;

--6 
SELECT TT_NAME
FROM
(SELECT TUTORS.TT_NAME, MIN(EDUCATION.ED_MARK)
FROM EDUCATION
LEFT JOIN STUDENTS
ON EDUCATION.ED_STUDENT = STUDENTS.ST_ID
LEFT JOIN TUTORS
ON EDUCATION.ED_TUTOR = TUTORS.TT_ID
WHERE STUDENTS.ST_NAME = 'Соколов С.С.' AND EDUCATION.ED_MARK IS NOT NULL
GROUP BY TUTORS.TT_NAME);

--7
SET SERVEROUTPUT ON
declare
  rows_found number ;
  any_rows_found NUMBER;
begin

  SELECT COUNT(EDUCATION.ED_ID) INTO rows_found
  FROM EDUCATION
  LEFT JOIN CLASSES_TYPES
  ON EDUCATION.ED_CLASS_TYPE = CLASSES_TYPES.CT_ID
  WHERE CLASSES_TYPES.CT_NAME <> 'Лабораторная работа' AND CLASSES_TYPES.CT_NAME <> 'Экзамен' AND EDUCATION.ED_MARK IS NOT NULL;

  if rows_found >0 then any_rows_found := 1;
  else
    any_rows_found := 0;
  end if;
  
  dbms_output.Put_line(any_rows_found);
  
END any_rows_found;
/

--QUERY
SELECT CASE WHEN EXISTS(
SELECT EDUCATION.ED_ID
FROM EDUCATION
LEFT JOIN CLASSES_TYPES
ON EDUCATION.ED_CLASS_TYPE = CLASSES_TYPES.CT_ID
WHERE CLASSES_TYPES.CT_NAME <> 'Лабораторная работа' AND CLASSES_TYPES.CT_NAME <> 'Экзамен' AND EDUCATION.ED_MARK IS NOT NULL)  
THEN 1
ELSE 0
END AS ANSWER
FROM DUAL;

--8
SELECT SHORT_DATE, LISTAGG(convert(SB_NAME, 'UTF8', 'AL16UTF16'), ',') within group (ORDER BY SHORT_DATE), CLASSES_NUMBER
FROM
(SELECT SB_NAME, TO_CHAR(ED_DATE, 'YYYY-MM') AS SHORT_DATE, COUNT( OUTER_TAB.ED_ID) AS CLASSES_NUMBER
FROM EDUCATION OUTER_TAB
JOIN SUBJECTS ON (OUTER_TAB.ED_SUBJECT = SUBJECTS.SB_ID)
WHERE EXTRACT(YEAR FROM OUTER_TAB.ED_DATE) = 2012
GROUP BY SB_NAME, TO_CHAR(ED_DATE, 'YYYY-MM')
HAVING COUNT(OUTER_TAB.ED_ID) = 
  ( SELECT MAX(COUNT(ED_ID)) 
    FROM EDUCATION
    WHERE TO_CHAR(EDUCATION.ED_DATE, 'YYYY-MM') = TO_CHAR(OUTER_TAB.ED_DATE, 'YYYY-MM')
    GROUP BY EDUCATION.ED_SUBJECT, TO_CHAR(ED_DATE, 'YYYY-MM')
    )
    )
GROUP BY SHORT_DATE,CLASSES_NUMBER
ORDER BY SHORT_DATE DESC;

--9
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME, AVG(EDUCATION.ED_MARK)
FROM EDUCATION
JOIN STUDENTS ON EDUCATION.ED_STUDENT = STUDENTS.ST_ID
GROUP BY STUDENTS.ST_ID, STUDENTS.ST_NAME
HAVING AVG(EDUCATION.ED_MARK) < (SELECT AVG(EDUCATION.ED_MARK) FROM EDUCATION )
ORDER BY STUDENTS.ST_ID;

--10
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME 
FROM STUDENTS
WHERE ST_ID NOT IN (
SELECT EDUCATION.ED_STUDENT
FROM EDUCATION
JOIN SUBJECTS ON EDUCATION.ED_SUBJECT = SUBJECTS.SB_ID
WHERE SUBJECTS.SB_NAME = 'Химия' OR SUBJECTS.SB_NAME = 'Физика');

--11
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME 
FROM STUDENTS
WHERE ST_ID NOT IN (
SELECT STUDENTS.ST_ID
FROM EDUCATION
JOIN STUDENTS ON EDUCATION.ED_STUDENT = STUDENTS.ST_ID AND (EDUCATION.ED_MARK = 10))
ORDER BY STUDENTS.ST_ID;

--12
SELECT SUBJECTS.SB_ID, SUBJECTS.SB_NAME, AVG(EDUCATION.ED_MARK)
FROM EDUCATION
RIGHT JOIN SUBJECTS ON EDUCATION.ED_SUBJECT = SUBJECTS.SB_ID
GROUP BY SUBJECTS.SB_ID, SUBJECTS.SB_NAME
HAVING AVG(EDUCATION.ED_MARK) > (SELECT AVG(EDUCATION.ED_MARK) FROM EDUCATION )
ORDER BY SUBJECTS.SB_ID;

--13
SELECT  SUBJECTS.SB_ID, SUBJECTS.SB_NAME, TO_CHAR(CLASSES_PER_MONTH, '0.0000') AS CLASSES_PER_MONTH
FROM SUBJECTS 
JOIN 
(SELECT ED_SUBJECT, COUNT(ED_ID) / MONTHS_BETWEEN(MAX(ED_DATE),MIN(ED_DATE)) AS CLASSES_PER_MONTH
FROM EDUCATION
GROUP BY ED_SUBJECT)
ON SUBJECTS.SB_ID = ED_SUBJECT
ORDER BY SUBJECTS.SB_ID;


--14
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME,
       SUBJECTS.SB_ID, SUBJECTS.SB_NAME, AVG(OUTER_ED.ED_MARK) AS AVG FROM EDUCATION OUTER_ED
    JOIN STUDENTS ON STUDENTS.ST_ID = OUTER_ED.ED_STUDENT
    JOIN SUBJECTS ON SUBJECTS.SB_ID = OUTER_ED.ED_SUBJECT 
    WHERE NOT EXISTS 
        (SELECT * FROM EDUCATION INNER_ED
            JOIN CLASSES_TYPES ON CLASSES_TYPES.CT_ID = INNER_ED.ED_CLASS_TYPE
                          AND CLASSES_TYPES.CT_NAME = 'ЭКЗАМЕН'
            WHERE INNER_ED.ED_STUDENT = OUTER_ED.ED_STUDENT
                  AND INNER_ED.ED_SUBJECT = OUTER_ED.ED_SUBJECT)
GROUP BY STUDENTS.ST_ID, STUDENTS.ST_NAME, SUBJECTS.SB_ID, SUBJECTS.SB_NAME
ORDER BY AVG DESC NULLS LAST; 

--15
SELECT TUTORS.TT_ID, TUTORS.TT_NAME, COUNT (ED_CLASS_TYPE) AS CLASSES
FROM EDUCATION
RIGHT JOIN TUTORS ON ED_TUTOR = TUTORS.TT_ID
GROUP BY TUTORS.TT_ID, TUTORS.TT_NAME
ORDER BY TT_ID;

--16
SELECT TUTORS.TT_ID, TUTORS.TT_NAME
FROM EDUCATION
RIGHT JOIN TUTORS ON ED_TUTOR = TUTORS.TT_ID
GROUP BY TUTORS.TT_ID, TUTORS.TT_NAME
HAVING COUNT(ED_MARK) = 0;

--17
SELECT TUTORS.TT_ID, TUTORS.TT_NAME, COUNT(ED_MARK) AS MARKS
FROM EDUCATION
RIGHT JOIN TUTORS ON ED_TUTOR = TUTORS.TT_ID
GROUP BY TUTORS.TT_ID, TUTORS.TT_NAME
ORDER BY MARKS DESC;

--18
SELECT SUBJECTS.SB_NAME, STUDENTS.ST_NAME, ROUND(AVG(ED_MARK), 4) AS AVERAGE
FROM EDUCATION
JOIN STUDENTS ON ED_STUDENT = STUDENTS.ST_ID
JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
GROUP BY SUBJECTS.SB_NAME, STUDENTS.ST_NAME
ORDER BY SUBJECTS.SB_NAME, AVERAGE DESC NULLS LAST;

--19
SELECT STUDENTS.ST_NAME, TO_CHAR(ED_DATE, 'YYYYMM'), ROUND(AVG(ED_MARK),4)
FROM EDUCATION
JOIN STUDENTS ON STUDENTS.ST_ID = EDUCATION.ED_STUDENT
GROUP BY STUDENTS.ST_NAME, TO_CHAR(ED_DATE, 'YYYYMM')
ORDER BY STUDENTS.ST_NAME, AVG(ED_MARK) DESC NULLS LAST;

--20
SELECT STUDENTS.ST_NAME, MAX(ED_MARK)AS MAX
FROM EDUCATION
JOIN STUDENTS ON STUDENTS.ST_ID = EDUCATION.ED_STUDENT
GROUP BY STUDENTS.ST_NAME
ORDER BY MAX DESC, STUDENTS.ST_NAME;

--21
SELECT STUDENTS.ST_NAME, COUNT(ED_MARK) AS BAD_MARKS
FROM EDUCATION
JOIN STUDENTS ON STUDENTS.ST_ID = EDUCATION.ED_STUDENT
WHERE ED_MARK < 5
GROUP BY STUDENTS.ST_NAME
HAVING COUNT(ED_MARK) = (SELECT MAX(COUNT) FROM 
(SELECT COUNT(ED_MARK) AS COUNT FROM EDUCATION WHERE ED_MARK < 5 GROUP BY ED_STUDENT));

--22
SELECT ST_ID, ST_NAME, COUNT (ED_ID) AS C
FROM STUDENTS 
JOIN EDUCATION
ON (ST_ID = ED_STUDENT)
GROUP BY ST_ID, ST_NAME
HAVING COUNT (ED_ID) = 
	(SELECT MAX(CC) 
		FROM (
		SELECT COUNT (ED_ID) AS CC
		FROM EDUCATION
		GROUP BY EDUCATION.ED_STUDENT)
	);	
	
--23
SELECT TT_ID, TT_NAME, COUNT(ED_ID)
FROM TUTORS
LEFT JOIN EDUCATION
ON TT_ID = ED_TUTOR
GROUP BY TT_ID, TT_NAME
ORDER BY COUNT(ED_ID) DESC;

--24
SELECT STUDENTS.ST_NAME, CLASSES FROM STUDENTS 
    JOIN
        (SELECT OUTER_ED.ED_STUDENT, COUNT(*) AS CLASSES FROM EDUCATION OUTER_ED
            GROUP BY OUTER_ED.ED_STUDENT
            HAVING COUNT(*) > ALL(
                (SELECT COUNT(*) FROM EDUCATION INNER_ED 
                    WHERE (INNER_ED.ED_STUDENT <> OUTER_ED.ED_STUDENT) 
                    GROUP BY INNER_ED.ED_STUDENT)))
    ON STUDENTS.ST_ID = ED_STUDENT;

--25
SELECT TUTORS.TT_NAME, SUBJECTS.SB_NAME, STUDENTS.ST_NAME, MAX(ED_MARK)
FROM EDUCATION
JOIN TUTORS ON ED_TUTOR = TUTORS.TT_ID
JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
JOIN STUDENTS ON ED_STUDENT = STUDENTS.ST_ID
WHERE ED_MARK IS NOT NULL
GROUP BY TUTORS.TT_NAME, SUBJECTS.SB_NAME,STUDENTS.ST_NAME
ORDER BY TUTORS.TT_NAME DESC, SUBJECTS.SB_NAME DESC, STUDENTS.ST_NAME DESC;

--26
SELECT STUDENTS.ST_NAME, SUM(ED_MARK)
FROM EDUCATION
JOIN STUDENTS ON STUDENTS.ST_ID = EDUCATION.ED_STUDENT
GROUP BY STUDENTS.ST_NAME
HAVING SUM(ED_MARK) = (
            SELECT MIN(SUM) 
            FROM (SELECT SUM(ED_MARK) AS SUM FROM EDUCATION GROUP BY ED_STUDENT));


--27
SELECT SUBJECTS.SB_NAME, COUNT(ED_SUBJECT)
FROM EDUCATION
RIGHT JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
WHERE ED_MARK IS NULL
AND ED_CLASS_TYPE IS NULL
GROUP BY SUBJECTS.SB_NAME;


--28
SELECT ED_ID, ED_STUDENT, ED_TUTOR, ED_SUBJECT, ED_CLASS_TYPE, ED_MARK, TO_CHAR(ED_DATE, 'YYYY-MM-DD HH24:MI:SS')
FROM EDUCATION
JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
AND SUBJECTS.SB_NAME = 'Химия'
JOIN CLASSES_TYPES ON ED_CLASS_TYPE = CLASSES_TYPES.CT_ID
AND CLASSES_TYPES.CT_NAME = 'Лабораторная работа'
WHERE ED_MARK IS NULL;

--29
SELECT SUBJECTS.SB_NAME, COUNT(ED_CLASS_TYPE)
FROM EDUCATION
JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
JOIN CLASSES_TYPES ON ED_CLASS_TYPE = CLASSES_TYPES.CT_ID
AND CLASSES_TYPES.CT_NAME = 'Экзамен'
WHERE 2012 = EXTRACT(YEAR FROM ed_date)
GROUP BY SUBJECTS.SB_NAME
HAVING COUNT(ED_CLASS_TYPE) = (
            SELECT MAX(COUNT) 
            FROM (SELECT COUNT(ED_CLASS_TYPE) AS COUNT FROM EDUCATION
            JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
            JOIN CLASSES_TYPES ON ED_CLASS_TYPE = CLASSES_TYPES.CT_ID
            AND CLASSES_TYPES.CT_NAME = 'Экзамен'
            WHERE 2012 = EXTRACT(YEAR FROM ED_DATE)
            GROUP BY ED_SUBJECT));

--30
SELECT SUBJECTS.SB_ID, SUBJECTS.SB_NAME, ROUND(COUNT(ED_CLASS_TYPE) / 12, 4)AS EXAMS_PER_MONTH
FROM EDUCATION
JOIN SUBJECTS ON ED_SUBJECT = SUBJECTS.SB_ID
AND SUBJECTS.SB_NAME = 'Программирование'
JOIN CLASSES_TYPES ON ED_CLASS_TYPE = CLASSES_TYPES.CT_ID
AND CLASSES_TYPES.CT_NAME = 'Экзамен'
GROUP BY SUBJECTS.SB_ID, SUBJECTS.SB_NAME;


