/* PRODUCT  */ 

CREATE TABLE PRODUCT (
	ID INTEGER  PRIMARY KEY,
	NAME NVARCHAR2(100) NOT NULL,
	BRAND NVARCHAR2(100) NOT NULL,
	PRICE INTEGER NOT NULL,
	DESCRIPTION varchar2(100) 
);

CREATE sequence PRODUCT_SEQ START WITH 1;

CREATE trigger PRODUCT_TRG
  before insert on PRODUCT
  for each row
begin
  select PRODUCT_SEQ.nextval into :NEW.id from dual;
end; 
/

/* CLIENT  */ 

CREATE TABLE CLIENT (
	ID INTEGER PRIMARY KEY,
	full_name NVARCHAR2(50),
	personal_Discount smallint,
	email NVARCHAR2(50),
  constraint discount_constraint CHECK (personal_Discount BETWEEN 0 and 100)
);

CREATE SEQUENCE CLIENT_SEQ START WITH 1;

CREATE TRIGGER CLIENT_TRG
  BEFORE INSERT ON CLIENT
  FOR EACH ROW
BEGIN 
  SELECT CLIENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

/* DISCOUNT  */ 

CREATE TABLE DISCOUNT (
	ID INT PRIMARY KEY,
	NAME NVARCHAR2(50) NOT NULL,
	DESCRIPTION NVARCHAR2(50),
	APPLY_TO_ALL NUMBER(1,0) NOT NULL,
  CONSTRAINT BOOL_CONSTRAINT CHECK (APPLY_TO_ALL BETWEEN 0 AND 1)
);

CREATE SEQUENCE DISCOUNT_SEQ START WITH 1;

CREATE TRIGGER DISCOUNT_TRG
  BEFORE INSERT ON DISCOUNT
  FOR EACH ROW
BEGIN 
  SELECT DISCOUNT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

/* ORDER_PRODUCT  */ 

CREATE TABLE order_product (
	ORDER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
  constraint PRIMARY_KEY PRIMARY KEY(ORDER_ID,PRODUCT_ID)
);

/* PRODUCT_DISCOUNT  */ 

CREATE TABLE product_discount (
	PRODUCT_ID INT,
	DISCOUNT_ID INT,
  constraint PRIMARY_KEY PRIMARY KEY(PRODUCT_ID,DISCOUNT_ID)
);

/* RECALL */

CREATE TABLE RECALL (
	ID INTEGER PRIMARY KEY,
	PRODUCT_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	MARK smallint NOT NULL,
	RECALL_COMMENT NVARCHAR2(1000),
	RECALL_DATE TIMESTAMP NOT NULL,
  CONSTRAINT MARK_CONSTRAINT CHECK(MARK BETWEEN 1 AND 5)
);

CREATE SEQUENCE RECALL_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE trigger RECALL_TRG
  before insert on RECALL
  for each row
begin
  select RECALL_SEQ.nextval into :NEW.id from dual;
end; 
/



